// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.DetailView.estimateID")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.DetailView.EstimateKeys")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.DetailView.Utility")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.Estimates.Estimates.Utility")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.PurchaseOrders.PODetails.poID")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.PurchaseOrders.PODetails.poKeys")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.PurchaseOrders.PODetails.Utility")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.PurchaseOrders.PurchaseOrders.Utility")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.salesOrderID")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.SalesOrderKeys")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.Utility")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrders.Utility")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.ViewModels.Toolkit.openFolder(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.ViewModels.Toolkit.openFolder(System.String)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.ViewModels.Toolkit.SetPrimaryKeys(System.Data.DataTable)")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.ViewModels.Toolkit.useQuery(System.String)~System.Data.DataTable")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.ViewModels.Toolkit.useQuery(System.String)~System.Data.DataTable")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.ViewModels.Toolkit.useQuery(System.String)~System.Data.DataTable")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.fillInfo")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.fillInfo")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.fillInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.fillInfo")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.fillInfo")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.GoToFolder(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.GoToFolder(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.itemNumbersForBOM")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.itemNumbersForBOM")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.laborDetails(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.materialDetails")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.OpenSalesorder(System.Object,System.Windows.Input.MouseButtonEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.updateVendor(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.DetailView.updateVendor(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.Estimates.Estimates.executeSearch(System.Object,System.Windows.Input.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.Estimates.Estimates.findCell(System.String,System.Data.DataView,System.Windows.Controls.DataGrid)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.PurchaseOrders.PODetails.fillInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.PurchaseOrders.PODetails.fillInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.PurchaseOrders.PurchaseOrders.findCell(System.String,System.Data.DataView,System.Windows.Controls.DataGrid)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.PurchaseOrders.PurchaseOrders.oSearchFor_KeyUp(System.Object,System.Windows.Input.KeyEventArgs)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.#ctor(System.String,System.Data.DataRow)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.#ctor(System.String,System.Data.DataRow)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.fillInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.fillInfo")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.fillInfo")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.fillInfo")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.fillInfo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.getItemSpecs")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.getItemSpecs")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.itemNumbersForBOM")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.itemNumbersForBOM")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.itemNumbersForBOM")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.laborDetails(System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.LineItems_SelectionChanged(System.Object,System.Windows.Controls.SelectionChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.materialDetails")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.openFolder(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.openFolder(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.openFolder(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails.updateVendor(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrders.executeSearch(System.Object,System.Windows.Input.KeyEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrders.findCell(System.String,System.Data.DataView,System.Windows.Controls.DataGrid)")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:LSGDatabox.Views.DetailView")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:LSGDatabox.Views.ViewPages.PurchaseOrders.PODetails")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:LSGDatabox.Views.ViewPages.SalesOrders.SalesOrderDetails")]
